apiVersion: v1
kind: ConfigMap
metadata:
  name: dyn-proxy-go-config
  labels:
    app: dyn-proxy-go
data:
  TARGET_HOST: "httpbin.org" # sample use httpbin.org for testing
  TARGET_PORT: "443"
  TARGET_SCHEME: "https"
  SNI: "httpbin.org"
  LOG_LEVEL: "debug"
  READ_TIMEOUT: "30"
  WRITE_TIMEOUT: "30"
  IDLE_TIMEOUT: "120"
  SKIP_TLS_VERIFY: "false"
  PAGE_TITLE: "Dyn-Proxy-Go with httpbin.org"
  SUB_TITLE: "Click on your proxy to navigate through it"
  PROXY_LIST: |
    proxyList:
      - name: UUID
        path: uuid                    
      - name: Get
        path: get        
      - name: Anything
        path: anything 
